/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javacompiler.app;

import static javacompiler.typechecker.Typecheck.typecheck;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
